Write error messages to stderr in makepkgmeta.

diff --git a/bin/makepkgmeta b/bin/makepkgmeta
--- a/bin/makepkgmeta
+++ b/bin/makepkgmeta
@@ -69,8 +69,10 @@ do
 	0)	basicmeta $1
 		exit 0 ;;
 	1)	;; # loop
-	2)	echo "error: $flav encountered an error"; exit 2 ;;
-	*)	echo "error: $flav returned error code $metaret"; exit 2 ;;
+	2)	echo "error: $flav encountered an error" 1>&2
+		exit 2 ;;
+	*)	echo "error: $flav returned error code $metaret" 1>&2
+		exit 2 ;;
 	esac
 done
 
